name: Build iOS Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        brew install make
        brew install ldid

    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        cd $HOME/theos
        bash ./install

    - name: Setup iOS SDK
      run: |
        git clone https://github.com/theos/sdks.git $HOME/theos/sdks

    - name: Build Project for iOS 26
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        export ARCHS=arm64
        export TARGET=iphone:clang:latest:26
        cd $GITHUB_WORKSPACE
        make  FINALPACKAGE=1

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: iOS-Tweak-Package-iOS26
        path: packages/*.deb
        if-no-files-found: warn
